<?php

namespace app\widgets;

use yii\helpers\Html;

/**
 * Widget for creating bootstrap glyphicons
 * @package frontend\widgets
 *
 * @method static asterisk(array $options = [])
 * @method static plus(array $options = [])
 * @method static minus(array $options = [])
 * @method static eur(array $options = [])
 * @method static euro(array $options = [])
 * @method static cloud(array $options = [])
 * @method static envelope(array $options = [])
 * @method static pencil(array $options = [])
 * @method static glass(array $options = [])
 * @method static music(array $options = [])
 * @method static search(array $options = [])
 * @method static heart(array $options = [])
 * @method static star(array $options = [])
 * @method static star_empty(array $options = [])
 * @method static user(array $options = [])
 * @method static film(array $options = [])
 * @method static th_large(array $options = [])
 * @method static th(array $options = [])
 * @method static th_list(array $options = [])
 * @method static ok(array $options = [])
 * @method static remove(array $options = [])
 * @method static zoom_in(array $options = [])
 * @method static zoom_out(array $options = [])
 * @method static off(array $options = [])
 * @method static signal(array $options = [])
 * @method static cog(array $options = [])
 * @method static trash(array $options = [])
 * @method static home(array $options = [])
 * @method static file(array $options = [])
 * @method static time(array $options = [])
 * @method static road(array $options = [])
 * @method static download_alt(array $options = [])
 * @method static download(array $options = [])
 * @method static upload(array $options = [])
 * @method static inbox(array $options = [])
 * @method static play_circle(array $options = [])
 * @method static repeat(array $options = [])
 * @method static refresh(array $options = [])
 * @method static list_alt(array $options = [])
 * @method static lock(array $options = [])
 * @method static flag(array $options = [])
 * @method static headphones(array $options = [])
 * @method static volume_off(array $options = [])
 * @method static volume_down(array $options = [])
 * @method static volume_up(array $options = [])
 * @method static qrcode(array $options = [])
 * @method static barcode(array $options = [])
 * @method static tag(array $options = [])
 * @method static tags(array $options = [])
 * @method static book(array $options = [])
 * @method static bookmark(array $options = [])
 * @method static print(array $options = [])
 * @method static camera(array $options = [])
 * @method static font(array $options = [])
 * @method static bold(array $options = [])
 * @method static italic(array $options = [])
 * @method static text_height(array $options = [])
 * @method static text_width(array $options = [])
 * @method static align_left(array $options = [])
 * @method static align_center(array $options = [])
 * @method static align_right(array $options = [])
 * @method static align_justify(array $options = [])
 * @method static list(array $options = [])
 * @method static indent_left(array $options = [])
 * @method static indent_right(array $options = [])
 * @method static facetime_video(array $options = [])
 * @method static picture(array $options = [])
 * @method static map_marker(array $options = [])
 * @method static adjust(array $options = [])
 * @method static tint(array $options = [])
 * @method static edit(array $options = [])
 * @method static share(array $options = [])
 * @method static check(array $options = [])
 * @method static move(array $options = [])
 * @method static step_backward(array $options = [])
 * @method static fast_backward(array $options = [])
 * @method static backward(array $options = [])
 * @method static play(array $options = [])
 * @method static pause(array $options = [])
 * @method static stop(array $options = [])
 * @method static forward(array $options = [])
 * @method static fast_forward(array $options = [])
 * @method static step_forward(array $options = [])
 * @method static eject(array $options = [])
 * @method static chevron_left(array $options = [])
 * @method static chevron_right(array $options = [])
 * @method static plus_sign(array $options = [])
 * @method static minus_sign(array $options = [])
 * @method static remove_sign(array $options = [])
 * @method static ok_sign(array $options = [])
 * @method static question_sign(array $options = [])
 * @method static info_sign(array $options = [])
 * @method static screenshot(array $options = [])
 * @method static remove_circle(array $options = [])
 * @method static ok_circle(array $options = [])
 * @method static ban_circle(array $options = [])
 * @method static arrow_left(array $options = [])
 * @method static arrow_right(array $options = [])
 * @method static arrow_up(array $options = [])
 * @method static arrow_down(array $options = [])
 * @method static share_alt(array $options = [])
 * @method static resize_full(array $options = [])
 * @method static resize_small(array $options = [])
 * @method static exclamation_sign(array $options = [])
 * @method static gift(array $options = [])
 * @method static leaf(array $options = [])
 * @method static fire(array $options = [])
 * @method static eye_open(array $options = [])
 * @method static eye_close(array $options = [])
 * @method static warning_sign(array $options = [])
 * @method static plane(array $options = [])
 * @method static calendar(array $options = [])
 * @method static random(array $options = [])
 * @method static comment(array $options = [])
 * @method static magnet(array $options = [])
 * @method static chevron_up(array $options = [])
 * @method static chevron_down(array $options = [])
 * @method static retweet(array $options = [])
 * @method static shopping_cart(array $options = [])
 * @method static folder_close(array $options = [])
 * @method static folder_open(array $options = [])
 * @method static resize_vertical(array $options = [])
 * @method static resize_horizontal(array $options = [])
 * @method static hdd(array $options = [])
 * @method static bullhorn(array $options = [])
 * @method static bell(array $options = [])
 * @method static certificate(array $options = [])
 * @method static thumbs_up(array $options = [])
 * @method static thumbs_down(array $options = [])
 * @method static hand_right(array $options = [])
 * @method static hand_left(array $options = [])
 * @method static hand_up(array $options = [])
 * @method static hand_down(array $options = [])
 * @method static circle_arrow_right(array $options = [])
 * @method static circle_arrow_left(array $options = [])
 * @method static circle_arrow_up(array $options = [])
 * @method static circle_arrow_down(array $options = [])
 * @method static globe(array $options = [])
 * @method static wrench(array $options = [])
 * @method static tasks(array $options = [])
 * @method static filter(array $options = [])
 * @method static briefcase(array $options = [])
 * @method static fullscreen(array $options = [])
 * @method static dashboard(array $options = [])
 * @method static paperclip(array $options = [])
 * @method static heart_empty(array $options = [])
 * @method static link(array $options = [])
 * @method static phone(array $options = [])
 * @method static pushpin(array $options = [])
 * @method static usd(array $options = [])
 * @method static gbp(array $options = [])
 * @method static sort(array $options = [])
 * @method static sort_by_alphabet(array $options = [])
 * @method static sort_by_alphabet_alt(array $options = [])
 * @method static sort_by_order(array $options = [])
 * @method static sort_by_order_alt(array $options = [])
 * @method static sort_by_attributes(array $options = [])
 * @method static sort_by_attributes_alt(array $options = [])
 * @method static unchecked(array $options = [])
 * @method static expand(array $options = [])
 * @method static collapse_down(array $options = [])
 * @method static collapse_up(array $options = [])
 * @method static log_in(array $options = [])
 * @method static flash(array $options = [])
 * @method static log_out(array $options = [])
 * @method static new_window(array $options = [])
 * @method static record(array $options = [])
 * @method static save(array $options = [])
 * @method static open(array $options = [])
 * @method static saved(array $options = [])
 * @method static import(array $options = [])
 * @method static export(array $options = [])
 * @method static send(array $options = [])
 * @method static floppy_disk(array $options = [])
 * @method static floppy_saved(array $options = [])
 * @method static floppy_remove(array $options = [])
 * @method static floppy_save(array $options = [])
 * @method static floppy_open(array $options = [])
 * @method static credit_card(array $options = [])
 * @method static transfer(array $options = [])
 * @method static cutlery(array $options = [])
 * @method static header(array $options = [])
 * @method static compressed(array $options = [])
 * @method static earphone(array $options = [])
 * @method static phone_alt(array $options = [])
 * @method static tower(array $options = [])
 * @method static stats(array $options = [])
 * @method static sd_video(array $options = [])
 * @method static hd_video(array $options = [])
 * @method static subtitles(array $options = [])
 * @method static sound_stereo(array $options = [])
 * @method static sound_dolby(array $options = [])
 * @method static sound_5_1(array $options = [])
 * @method static sound_6_1(array $options = [])
 * @method static sound_7_1(array $options = [])
 * @method static copyright_mark(array $options = [])
 * @method static registration_mark(array $options = [])
 * @method static cloud_download(array $options = [])
 * @method static cloud_upload(array $options = [])
 * @method static tree_conifer(array $options = [])
 * @method static tree_deciduous(array $options = [])
 * @method static cd(array $options = [])
 * @method static save_file(array $options = [])
 * @method static open_file(array $options = [])
 * @method static level_up(array $options = [])
 * @method static copy(array $options = [])
 * @method static paste(array $options = [])
 * @method static alert(array $options = [])
 * @method static equalizer(array $options = [])
 * @method static king(array $options = [])
 * @method static queen(array $options = [])
 * @method static pawn(array $options = [])
 * @method static bishop(array $options = [])
 * @method static knight(array $options = [])
 * @method static baby_formula(array $options = [])
 * @method static tent(array $options = [])
 * @method static blackboard(array $options = [])
 * @method static bed(array $options = [])
 * @method static apple(array $options = [])
 * @method static erase(array $options = [])
 * @method static hourglass(array $options = [])
 * @method static lamp(array $options = [])
 * @method static duplicate(array $options = [])
 * @method static piggy_bank(array $options = [])
 * @method static scissors(array $options = [])
 * @method static bitcoin(array $options = [])
 * @method static yen(array $options = [])
 * @method static ruble(array $options = [])
 * @method static scale(array $options = [])
 * @method static ice_lolly(array $options = [])
 * @method static ice_lolly_tasted(array $options = [])
 * @method static education(array $options = [])
 * @method static option_horizontal(array $options = [])
 * @method static option_vertical(array $options = [])
 * @method static menu_hamburger(array $options = [])
 * @method static modal_window(array $options = [])
 * @method static oil(array $options = [])
 * @method static grain(array $options = [])
 * @method static sunglasses(array $options = [])
 * @method static text_size(array $options = [])
 * @method static text_color(array $options = [])
 * @method static text_background(array $options = [])
 * @method static object_align_top(array $options = [])
 * @method static object_align_bottom(array $options = [])
 * @method static object_align_horizontal(array $options = [])
 * @method static object_align_left(array $options = [])
 * @method static object_align_vertical(array $options = [])
 * @method static object_align_right(array $options = [])
 * @method static triangle_right(array $options = [])
 * @method static triangle_left(array $options = [])
 * @method static triangle_bottom(array $options = [])
 * @method static triangle_top(array $options = [])
 * @method static console(array $options = [])
 * @method static superscript(array $options = [])
 * @method static subscript(array $options = [])
 * @method static menu_left(array $options = [])
 * @method static menu_right(array $options = [])
 * @method static menu_down(array $options = [])
 * @method static menu_up(array $options = [])
 */
class Glyphicon
{

    public static function __callStatic($name, $arguments)
    {
        return self::span(
            str_replace("_", "-", $name),
            isset($arguments[0]) ? $arguments[0] : []
        );
    }

    public static function span($glyphicon, array $options = [])
    {
        $classOption = isset($options["class"]) ? $options["class"] : "";
        unset($options["class"]);
        return Html::tag("span", "", array_merge([
            "class" => "glyphicon glyphicon-$glyphicon $classOption"
        ], $options));
    }

}